version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example # NOTE: This password is only for testing/learning purposes, do not use in production

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example # NOTE: This password is only for testing/learning purposes, do not use in production
      ME_CONFIG_MONGODB_SERVER: mongo


  backend:
    image: chucthien03/three-tier-backend:latest
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"

    environment: 
      MONGO_USER: root
      MONGO_PASS: example # NOTE: This password is only for testing/learning purposes, do not use in production
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: crud_demo

  frontend:
    image: chucthien03/three-tier-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      API_BASE_URL: "http://localhost:8000"




volumes:
  mongo_data: